### ISSUE TITLE
Return values

### ISSUE THREAD

**Issue by felixfbecker** [zelein/typed-valid-url#2]
The docs say

> All functions return an untainted value if the test passes, and undef if it fails. This means that you should always check for a defined status explicitly. Don't assume the return will be true

Therefor I think the return values should be `string | void`. I havent used the library though.

**Comment by zelein** [comment]
Yes, you are correct. I will add the void return to the return type. I tried adding undefined but I forgot that is a TS2.0 thing.

**Comment by felixfbecker** [comment]
Yeah you can update it once TS2 is out :)
It should be possible to narrow the type with
```ts
if (typeof ret === 'string') {
  ret.substr(4)
}
```
maybe add a test for that

**Comment by zelein** [comment]
If you look in the test/test.ts I do have an assert showing that if an invalid url is passed in it will return undefined. Is that sufficient?

**Comment by felixfbecker** [comment]
The point of tests for typings is not to test the functionality of the library, but to see if common use cases compile correctly without errors. I actually only write code and then call `tsc` to test my typings to see if there are errors, without any test runners. You can take a look at my typings if you want.

**Comment by zelein** [comment]
Thanks for the insight Felix. I've added the test in the latest commit [7a7191b549c3980951281794cba2496ab0b9af07](https://github.com/zelein/typed-valid-url/commit/7a7191b549c3980951281794cba2496ab0b9af07)

If there is nothing else I will close this issue.

**Comment by felixfbecker** [comment]
Seems fine. Btw, your Travis does not seem to work.

**Comment by zelein** [comment]
Oh yea I need to set up a travis account. that travis file in the repo came from the generator. I will do that in the future. Thanks.
